# ベースイメージとしてNode.jsを使用 (Pythonもインストール可能な軽量のLinuxベース)
FROM arm32v6/node:20.18.1-alpine3.20

# shadow Python homebridge homebridge-config-ui-x をインストール　 
RUN apk update \
    && apk add python3 py3-pip shadow \
    && npm install -g --unsafe-perm homebridge homebridge-config-ui-x

# homebridge_user というユーザを追加
RUN useradd -m -s /bin/sh homebridge_user

# 作業ディレクトリを設定
WORKDIR /home/homebridge_user

# Homebridgeを作成
RUN mkdir .homebridge
COPY ./config.json /.homebridge/config.json
RUN chown -R homebridge_user:homebridge_user /home/homebridge_user/.homebridge

# Homebridge 用にホストからのコンテナのポートをリンク
EXPOSE 51826  
# Homebridge UI 用にホストからのコンテナのポートをリンク
EXPOSE 8080

# デフォルトコマンドとしてHomebridgeを起動
USER homebridge_user
CMD ["homebridge"]
